# Generated by Django 5.0.1 on 2024-06-11 02:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_application_Number', models.IntegerField(blank=True, null=True)),
                ('tc_application_Year', models.IntegerField(blank=True, null=True)),
                ('tcNumber', models.IntegerField(blank=True, default=None, null=True)),
                ('tcYear', models.IntegerField(blank=True, default=None, null=True)),
                ('dateofIssue', models.DateField(auto_now=True, null=True)),
                ('conduct', models.CharField(default='Good', max_length=20)),
                ('reasonforLeaving', models.CharField(choices=[('Course discontinued', 'Course discontinued'), ('Got Another Allotment', 'Got Another Allotment'), ('Course Completed', 'Course Completed'), ('institution Transfer', 'Institution Transfer')], max_length=50)),
                ('dateofApplication', models.DateField(default=datetime.datetime.now)),
                ('promotionDate', models.DateField(default=datetime.datetime.now)),
                ('lastclass', models.IntegerField(default=6)),
                ('promotedtoHigherClass', models.CharField(choices=[('Yes', 'yes'), ('No', 'No'), ('Result Not Announced', 'Result Not announced')], default='Result Not Announced', max_length=30)),
                ('proceedingInstitution', models.CharField(default='Result Not Announced', max_length=100)),
                ('lastAttendedDate', models.DateField(default=datetime.datetime.now)),
                ('dateofremovedfromrolls', models.DateField(auto_now=True)),
                ('totalWorkingDay', models.IntegerField(default=0)),
                ('attendance', models.IntegerField(default=0)),
                ('duesCleared', models.BooleanField(default=True)),
                ('fee_concession', models.BooleanField(default=True)),
                ('tc_issued', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='TcIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcNumber', models.IntegerField()),
                ('tcYear', models.IntegerField()),
                ('tcApplication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tc.tcapplication')),
            ],
        ),
    ]
